# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:3.24 AS xvfb-builder

ARG XLIBRE_TAG=xlibre-xserver-25.2.2

RUN \
  echo "**** install xlibre build deps ****" && \
  apk add --no-cache \
    build-base \
    font-util-dev \
    git \
    libbsd-dev \
    libdrm-dev \
    libepoxy-dev \
    libx11-dev \
    libxau-dev \
    libxcvt-dev \
    libxdmcp-dev \
    libxext-dev \
    libxfont2-dev \
    libxkbfile-dev \
    libxshmfence-dev \
    mesa-dev \
    meson \
    nettle-dev \
    ninja \
    pixman-dev \
    pkgconf \
    xkbcomp-dev \
    xorgproto \
    xtrans

COPY patches/alpine/3.24/xvfb/ /patches/

RUN \
  echo "**** build xlibre xvfb ${XLIBRE_TAG} ****" && \
  git clone \
    --depth 1 \
    --branch ${XLIBRE_TAG} \
    https://github.com/X11Libre/xserver.git \
    /tmp/xserver && \
  cd /tmp/xserver && \
  for xvfb_patch in /patches/*.patch; do \
    [ -e "${xvfb_patch}" ] || continue; \
    echo "applying $(basename "${xvfb_patch}")" && \
    git apply "${xvfb_patch}"; \
  done && \
  meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dxvfb=true \
    -Dglamor=true \
    -Dgbm=true \
    -Ddri3=true \
    -Dglx=true \
    -Dxcsecurity=true \
    -Dxselinux=false \
    -Dxorg=false \
    -Dxnest=false \
    -Dxephyr=false \
    -Dxwin=false \
    -Dxquartz=false \
    -Dudev=false \
    -Dudev_kms=false \
    -Dsystemd_logind=false \
    -Dxkb_dir=/usr/share/X11/xkb \
    -Dxkb_output_dir=/var/lib/xkb \
    -Dxkb_bin_dir=/usr/bin \
    -Ddefault_font_path=/usr/share/fonts/misc,/usr/share/fonts/100dpi:unscaled,/usr/share/fonts/75dpi:unscaled,/usr/share/fonts/TTF,/usr/share/fonts/Type1,built-ins \
    -Ddocs=false \
    -Ddevel-docs=false && \
  ninja -C build hw/vfb/Xvfb && \
  echo "**** stage layer ****" && \
  install -Dm755 build/hw/vfb/Xvfb /buildout/usr/bin/Xvfb && \
  /buildout/usr/bin/Xvfb -help 2>&1 | grep -q -- '-glamor'

FROM scratch
COPY --from=xvfb-builder /buildout/ /
