# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-fedora:44 AS xvfb-builder

ARG XLIBRE_TAG=xlibre-xserver-25.2.2

RUN \
  echo "**** install xlibre build deps ****" && \
  dnf install -y \
    audit-libs-devel \
    gcc \
    git \
    libbsd-devel \
    libdrm-devel \
    libepoxy-devel \
    libselinux-devel \
    libX11-devel \
    libXau-devel \
    libxcvt-devel \
    libXdmcp-devel \
    libXext-devel \
    libXfont2-devel \
    libxkbfile-devel \
    libxshmfence-devel \
    make \
    mesa-libEGL-devel \
    mesa-libgbm-devel \
    mesa-libGL-devel \
    meson \
    ninja-build \
    openssl-devel \
    pixman-devel \
    pkgconf-pkg-config \
    xorg-x11-proto-devel \
    xorg-x11-util-macros \
    xorg-x11-xtrans-devel

COPY patches/fedora/44/xvfb/ /patches/

RUN \
  echo "**** build xlibre xvfb ${XLIBRE_TAG} ****" && \
  git clone \
    --depth 1 \
    --branch ${XLIBRE_TAG} \
    https://github.com/X11Libre/xserver.git \
    /tmp/xserver && \
  cd /tmp/xserver && \
  for xvfb_patch in /patches/*.patch; do \
    [ -e "${xvfb_patch}" ] || continue; \
    echo "applying $(basename "${xvfb_patch}")" && \
    git apply "${xvfb_patch}"; \
  done && \
  meson setup build \
    --prefix=/usr \
    --sysconfdir=/etc \
    --localstatedir=/var \
    --buildtype=release \
    -Dxvfb=true \
    -Dglamor=true \
    -Dgbm=true \
    -Ddri3=true \
    -Dglx=true \
    -Dxcsecurity=true \
    -Dxselinux=true \
    -Dsha1=libcrypto \
    -Dxorg=false \
    -Dxnest=false \
    -Dxephyr=false \
    -Dxwin=false \
    -Dxquartz=false \
    -Dudev=false \
    -Dudev_kms=false \
    -Dsystemd_logind=false \
    -Dxkb_dir=/usr/share/X11/xkb \
    -Dxkb_output_dir=/var/lib/xkb \
    -Dxkb_bin_dir=/usr/bin \
    -Ddefault_font_path=catalogue:/etc/X11/fontpath.d,built-ins \
    -Ddocs=false \
    -Ddevel-docs=false && \
  ninja -C build hw/vfb/Xvfb && \
  echo "**** stage layer ****" && \
  install -Dm755 build/hw/vfb/Xvfb /buildout/usr/bin/Xvfb && \
  /buildout/usr/bin/Xvfb -help 2>&1 | grep -q -- '-glamor'

FROM scratch
COPY --from=xvfb-builder /buildout/ /
