# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-arch:latest AS labwc-builder

ARG DISTRO_VERSION

RUN \
  echo "**** install labwc/wlroots build deps ****" && \
  pacman -Sy --noconfirm \
    base-devel \
    cairo \
    git \
    glib2 \
    glslang \
    hwdata \
    libdisplay-info \
    libdrm \
    libinput \
    libliftoff \
    librsvg \
    libsfdo \
    libx11 \
    libxcb \
    libxkbcommon \
    libxml2 \
    mesa \
    meson \
    ninja \
    pango \
    pixman \
    pkgconf \
    scdoc \
    seatd \
    systemd-libs \
    vulkan-headers \
    vulkan-icd-loader \
    wayland \
    wayland-protocols \
    xcb-util-errors \
    xcb-util-renderutil \
    xcb-util-wm \
    xorg-xwayland

RUN \
  echo "**** build wlroots 0.19.3 ****" && \
  git clone https://gitlab.freedesktop.org/wlroots/wlroots.git /tmp/wlroots && \
  cd /tmp/wlroots && \
  git checkout 0.19.3 && \
  meson setup build --prefix=/usr --libdir=lib -Dxwayland=enabled && \
  ninja -C build && \
  ninja -C build install

COPY patches/arch/${DISTRO_VERSION}/labwc/ /patches/

RUN \
  echo "**** build labwc 0.9.7 ****" && \
  git clone https://github.com/labwc/labwc.git /tmp/labwc && \
  cd /tmp/labwc && \
  git checkout 0.9.7 && \
  for labwc_patch in /patches/*.patch; do \
    [ -e "${labwc_patch}" ] || continue; \
    echo "applying $(basename "${labwc_patch}")" && \
    git apply "${labwc_patch}"; \
  done && \
  meson setup build --prefix=/usr --libdir=lib -Dxwayland=enabled -Dnls=enabled && \
  ninja -C build && \
  ninja -C build install && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin /buildout/usr/lib && \
  cp /usr/bin/labwc /buildout/usr/bin/labwc && \
  cp -a /usr/lib/libwlroots-0.19.so* /buildout/usr/lib/

FROM scratch
COPY --from=labwc-builder /buildout/ /
