# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-fedora:44 AS kwin-builder

ARG DISTRO_VERSION

COPY patches/fedora/${DISTRO_VERSION}/kwin/ /build/patches/

RUN \
  echo "**** install build packages ****" && \
  dnf install -y --setopt=install_weak_deps=False --best \
    dnf5-plugins \
    kf6-rpm-macros \
    rpm-build && \
  echo "**** fetch fedora kwin source package ****" && \
  mkdir -p /build/src && \
  dnf download -y --srpm --destdir=/build/src \
    kwin && \
  dnf builddep -y --setopt=install_weak_deps=False \
    /build/src/kwin-*.src.rpm && \
  rpm --define "_topdir /build/rpmbuild" -i \
    /build/src/kwin-*.src.rpm && \
  echo "**** add patches to the fedora spec ****" && \
  i=100 && \
  for kwin_patch in /build/patches/*.patch; do \
    [ -e "${kwin_patch}" ] || continue; \
    echo "adding $(basename "${kwin_patch}") as Patch${i}" && \
    cp "${kwin_patch}" /build/rpmbuild/SOURCES/ && \
    sed -i "/^Source1:/a Patch${i}: $(basename "${kwin_patch}")" \
      /build/rpmbuild/SPECS/kwin.spec && \
    i=$((i + 1)); \
  done && \
  sed -i \
    's/^%cmake_build$/%cmake_build --target kwin screencast/' \
    /build/rpmbuild/SPECS/kwin.spec && \
  echo "**** build patched kwin targets ****" && \
  rpmbuild --define "_topdir /build/rpmbuild" -bc --nodeps \
    /build/rpmbuild/SPECS/kwin.spec && \
  echo "**** stage layer ****" && \
  LIBDIR=/buildout/usr/lib64 && \
  mkdir -p \
    ${LIBDIR}/qt6/plugins/kwin/plugins && \
  cp \
    $(find /build/rpmbuild/BUILD -name 'libkwin.so.6.*' -type f) \
    ${LIBDIR}/ && \
  cp \
    $(find /build/rpmbuild/BUILD -name 'screencast.so' -type f) \
    ${LIBDIR}/qt6/plugins/kwin/plugins/ && \
  strip --strip-unneeded \
    --remove-section=.comment \
    --remove-section=.note \
    ${LIBDIR}/libkwin.so.6.* \
    ${LIBDIR}/qt6/plugins/kwin/plugins/screencast.so

FROM scratch
COPY --from=kwin-builder /buildout/ /
