# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-arch:latest AS wtype-builder

RUN \
  echo "**** install wtype build deps ****" && \
  pacman -Sy --noconfirm --needed \
    base-devel \
    cmake \
    git \
    libxkbcommon \
    meson \
    ninja \
    pkgconf \
    wayland

RUN \
  echo "**** build wtype ****" && \
  git clone \
    https://github.com/linuxserver/waylandtyper.git \
    /tmp/wtype && \
  cd /tmp/wtype && \
  make && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp wtype /buildout/usr/bin/wtype

FROM scratch
COPY --from=wtype-builder /buildout/ /
