# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-fedora:44 AS selkies-desktop-builder

RUN \
  echo "**** install selkies-desktop build deps ****" && \
  dnf install -y \
    cairo-devel \
    gcc \
    git \
    make \
    wayland-devel \
    wayland-protocols-devel

RUN \
  echo "**** build selkies-desktop ****" && \
  git clone \
    https://github.com/selkies-project/selkies-desktop.git \
    /tmp/selkies-desktop && \
  cd /tmp/selkies-desktop && \
  make && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp selkies-desktop /buildout/usr/bin/selkies-desktop

FROM scratch
COPY --from=selkies-desktop-builder /buildout/ /
