# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-arch:latest AS selkies-desktop-builder

RUN \
  echo "**** install selkies-desktop build deps ****" && \
  pacman -Sy --noconfirm --needed \
    base-devel \
    cairo \
    git \
    wayland \
    wayland-protocols

RUN \
  echo "**** build selkies-desktop ****" && \
  git clone \
    https://github.com/selkies-project/selkies-desktop.git \
    /tmp/selkies-desktop && \
  cd /tmp/selkies-desktop && \
  make && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp selkies-desktop /buildout/usr/bin/selkies-desktop

FROM scratch
COPY --from=selkies-desktop-builder /buildout/ /
