# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-alpine:3.24 AS selkies-desktop-builder

RUN \
  echo "**** install selkies-desktop build deps ****" && \
  apk add --no-cache \
    alpine-sdk \
    cairo-dev \
    git \
    wayland-dev \
    wayland-protocols

RUN \
  echo "**** build selkies-desktop ****" && \
  git clone \
    https://github.com/selkies-project/selkies-desktop.git \
    /tmp/selkies-desktop && \
  cd /tmp/selkies-desktop && \
  make && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp selkies-desktop /buildout/usr/bin/selkies-desktop

FROM scratch
COPY --from=selkies-desktop-builder /buildout/ /
