# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-arch:latest AS kwin-builder

ARG DISTRO_VERSION

COPY patches/arch/${DISTRO_VERSION}/kwin/ /build/patches/

RUN \
  echo "**** install build deps ****" && \
  pacman -Sy --noconfirm --needed \
    base-devel \
    cmake \
    extra-cmake-modules \
    kdoctools \
    krunner \
    kwin \
    plasma-wayland-protocols \
    python \
    vulkan-headers \
    wayland-protocols \
    xorg-xwayland && \
  echo "**** fetch arch kwin build recipe ****" && \
  KWIN_TAG=$(pacman -Q kwin | awk '{print $2}') && \
  mkdir -p /build/src && \
  cd /build/src && \
  curl -fLo PKGBUILD \
    https://gitlab.archlinux.org/archlinux/packaging/packages/kwin/-/raw/${KWIN_TAG}/PKGBUILD && \
  . ./PKGBUILD && \
  echo "**** fetch kwin ${pkgver} source ****" && \
  curl -fLo \
    kwin-${pkgver}.tar.xz \
    ${source[0]} && \
  echo "${sha256sums[0]}  kwin-${pkgver}.tar.xz" | sha256sum -c && \
  tar xf kwin-${pkgver}.tar.xz && \
  cd kwin-${pkgver}/ && \
  echo "**** build patched kwin targets ****" && \
  for kwin_patch in /build/patches/*.patch; do \
    [ -e "${kwin_patch}" ] || continue; \
    echo "applying $(basename "${kwin_patch}")" && \
    patch -p1 < "${kwin_patch}"; \
  done && \
  . /etc/makepkg.conf && \
  export CFLAGS CXXFLAGS LDFLAGS && \
  cmake -B build \
    -DCMAKE_INSTALL_LIBEXECDIR=lib \
    -DBUILD_TESTING=OFF && \
  cmake --build build --parallel $(nproc) --target \
    kwin \
    screencast && \
  echo "**** stage layer ****" && \
  LIBDIR=/buildout/usr/lib && \
  mkdir -p \
    ${LIBDIR}/qt6/plugins/kwin/plugins && \
  cp \
    $(find build -name 'libkwin.so.6.*' -type f) \
    ${LIBDIR}/ && \
  cp \
    $(find build -name 'screencast.so' -type f) \
    ${LIBDIR}/qt6/plugins/kwin/plugins/ && \
  strip --strip-unneeded \
    --remove-section=.comment \
    --remove-section=.note \
    ${LIBDIR}/libkwin.so.6.* \
    ${LIBDIR}/qt6/plugins/kwin/plugins/screencast.so

FROM scratch
COPY --from=kwin-builder /buildout/ /
