# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-debian:trixie AS selkies-desktop-builder

RUN \
  echo "**** install selkies-desktop build deps ****" && \
  apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libcairo2-dev \
    libwayland-dev \
    pkg-config \
    wayland-protocols

RUN \
  echo "**** build selkies-desktop ****" && \
  git clone \
    https://github.com/selkies-project/selkies-desktop.git \
    /tmp/selkies-desktop && \
  cd /tmp/selkies-desktop && \
  make && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp selkies-desktop /buildout/usr/bin/selkies-desktop

FROM scratch
COPY --from=selkies-desktop-builder /buildout/ /
