# syntax=docker/dockerfile:1

FROM ghcr.io/linuxserver/baseimage-fedora:44 AS labwc-builder

ARG DISTRO_VERSION

RUN \
  echo "**** install labwc build deps ****" && \
  dnf install -y \
    gcc \
    gcc-c++ \
    make \
    cairo-devel \
    systemd-devel \
    gettext-devel \
    git \
    glib2-devel \
    glslang-devel \
    hwdata \
    libdisplay-info-devel \
    libdrm-devel \
    libinput-devel \
    libliftoff-devel \
    librsvg2-devel \
    libX11-devel \
    libxcb-devel \
    libxkbcommon-devel \
    libxml2-devel \
    mesa-libGL-devel \
    mesa-libEGL-devel \
    mesa-libgbm-devel \
    meson \
    ninja-build \
    pango-devel \
    pixman-devel \
    pkgconf \
    scdoc \
    seatd \
    vulkan-headers \
    vulkan-loader-devel \
    wayland-devel \
    wayland-protocols-devel \
    wlroots0.19-devel \
    xcb-util-errors-devel \
    xcb-util-renderutil-devel \
    xcb-util-wm-devel \
    xorg-x11-server-Xwayland-devel

COPY patches/fedora/${DISTRO_VERSION}/labwc/ /patches/

RUN \
  echo "**** build labwc 0.9.7 ****" && \
  git clone https://github.com/labwc/labwc.git /tmp/labwc && \
  cd /tmp/labwc && \
  git checkout 0.9.7 && \
  for labwc_patch in /patches/*.patch; do \
    [ -e "${labwc_patch}" ] || continue; \
    echo "applying $(basename "${labwc_patch}")" && \
    git apply "${labwc_patch}"; \
  done && \
  meson setup build --prefix=/usr --libdir=lib -Dxwayland=enabled -Dnls=enabled && \
  ninja -C build && \
  ninja -C build install && \
  echo "**** stage layer ****" && \
  mkdir -p /buildout/usr/bin && \
  cp /usr/bin/labwc /buildout/usr/bin/labwc

FROM scratch
COPY --from=labwc-builder /buildout/ /
